# Generated by Django 4.2.2 on 2023-07-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chatmessage_parent_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('chemistry', 'Chemistry'), ('physics', 'Physics')], max_length=100)),
                ('file', models.FileField(upload_to='resources/')),
            ],
        ),
    ]
